# NumPy Library

- NumPy stands for Numerical Python
- NumPy is used for linear algebra operations

## Installing NumPy
- In command prompt type the following command to install numpy
```
pip install numpy
```

- In Jupyter Notebook to install numpy use the following command
```
!pip install numpy
```

### Using NumPy by importing it

In [115]:
import numpy

### What are you going to do with NumPy library
- We create arrays (numerical arrays) with many dimensions
- Such arrays are called: ndarray

### Import import with an alias name `np`

In [116]:
import numpy as np

In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr1

array([1, 2, 3, 4])

In [ ]:
type(arr1)

numpy.ndarray

In [119]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Four Basic Attributes of NumPy arrays

In [120]:
arr1

array([1, 2, 3, 4])

#### shape attribute gives an tuple with values to specify the shape

In [121]:
arr1.shape

(4,)

In [122]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [123]:
arr2.shape

(4, 3)

#### `ndim` to get number of dimensions

In [124]:
arr1

array([1, 2, 3, 4])

In [125]:
arr1.ndim

1

In [126]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [127]:
arr2.ndim

2

#### `size` - to get total number of elements

In [128]:
arr1

array([1, 2, 3, 4])

In [129]:
arr1.size

4

In [ ]:
arr2

In [ ]:
arr2.size

#### `dtype` - to know the datatype of the elements of an array

In [ ]:
arr1.dtype

In [ ]:
arr2.dtype

### `ones()` to create a array with ones

In [ ]:
np.ones((2, 5))

### zeros() to create an array with all zeros

In [ ]:
np.zeros((5, 12))

### `full()` to create an array with a defaul (fixed) values

In [ ]:
np.full((4, 3), 7)

### `eye()` to create an identity matrix (array)

In [ ]:
np.eye(3)

In [ ]:
np.eye(2)

In [ ]:
np.eye(4)

### Creating array with sequence of integers using - `arange()`
##### Syntax
```
arange([start, ]stop[, step])
```
- By default start is 0; and step is 1
- Stop is required

In [ ]:
np.arange(10)

In [ ]:
np.arange(1, 10, 2)

In [ ]:
np.arange(-100, 100, 25)

### Create a sequence of numbers that equally distant from each other using - `linspace`
```
linspace(start, end, num_of_values)
```

In [ ]:
np.linspace(0, 1, 5)

### Generate random values between 0 and 1, 1 is exlusive
```
np.random.rand(rows, cols)
```

In [ ]:
np.random.rand(4, 3)

### Generate an array with normal distribution

In [ ]:
np.random.randn(3, 5)

### Generate an array with random number

In [ ]:
np.random.randint(0, 10, (4, 8))

### Changing type of an array

In [ ]:
arr = np.array([1.2, 2.3, 3.4, 4.5])
arr.dtype

In [ ]:
arr = arr.astype(int)
arr

In [ ]:
arr.dtype

## INDEXING AND SLICING

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1[0])

In [ ]:
print(arr1[-1])

In [ ]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
arr2[0, :]

In [ ]:
arr2[1, 2]

In [ ]:
arr2[:, 1]

In [ ]:
arr2[1:, 1:]

### Boolean Indexing

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]

In [ ]:
mask

### Fancy indexing

In [ ]:
arr

In [ ]:
indexes = [0, 3, 4]
arr[indexes]

### Reshaping an array using reshape(rows, cols) method

In [ ]:
arr = np.arange(12)
arr

In [ ]:
arr.reshape(3, 4)

In [ ]:
arr.reshape(6, 2)

In [ ]:
arr.reshape(2, 6)

In [ ]:
arr.reshape(2, 2, 3)

In [ ]:
arr

In [ ]:
arr = arr.reshape(3, 4)
arr

### `flatten()` - make an array one-dimensional

In [ ]:
arr

In [ ]:
arr.flatten()

## NumPy Operations

### Element-wise Arithmetics

In [130]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [131]:
print(a + b)

[5 7 9]


In [132]:
print(a - b)

[-3 -3 -3]


In [133]:
print(a * b)

[ 4 10 18]


In [134]:
print( a / b)

[0.25 0.4  0.5 ]


In [135]:
print( a ** b)

[  1  32 729]


In [136]:
# working with scalars

In [137]:
a + 10

array([11, 12, 13])

In [138]:
b - 3

array([1, 2, 3])

### Universal functions

In [139]:
arr = np.array([1, 4, 9, 16])

In [140]:
np.sqrt(arr)

array([1., 2., 3., 4.])

In [141]:
np.log(arr)

array([0.        , 1.38629436, 2.19722458, 2.77258872])

In [142]:
np.exp(arr)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [143]:
np.sin(arr)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332])

In [144]:
np.cos(arr)

array([ 0.54030231, -0.65364362, -0.91113026, -0.95765948])

### Aggregate functions

In [145]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [146]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [147]:
arr.sum()

21

In [148]:
# axis - dimensions 2 (rows and columns) - axes (x-axis is 0, y-axis is 1)

In [151]:
arr.sum(axis=0)

array([5, 7, 9])

In [150]:
arr.sum(axis=1)

array([ 6, 15])

In [153]:
# mean(), max(), min()

### Broadcasting

In [154]:
# performing operatons on unequal arrays

In [155]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [156]:
add_vector = np.array([10, 20, 30])
add_vector

array([10, 20, 30])

In [157]:
arr + add_vector

array([[11, 22, 33],
       [14, 25, 36]])

### Comparison operators

In [158]:
arr = np.array([1, 2, 3, 4, 5])
arr >= 3

array([False, False,  True,  True,  True])

In [159]:
arr == 3

array([False, False,  True, False, False])

In [160]:
arr > 0

array([ True,  True,  True,  True,  True])

In [161]:
## any() and all() functions

In [162]:
np.any(arr == 3)   # if at least one value is True it returns True

True

In [163]:
np.all(arr == 3)  # if any value is False then it returns False

False

In [164]:
np.all(arr > 0)  # returns True when all the values are True

True

### Conditional Selection (where)

In [170]:
arr = np.array([10, 20, 30, 40])
result = np.where(arr > 25, 1, 0)   # 1 represent True; 0 represents False
result

array([0, 0, 1, 1])

### Non-zero Selection

In [173]:
arr = np.array([3, 0, 1, 4, 0])
indexes = np.nonzero(arr)
arr[indexes]

array([3, 1, 4])

### Sort the elements

In [174]:
arr = np.array([
    [3, 1, 9],
    [8, 7, 6]
])
arr

array([[3, 1, 9],
       [8, 7, 6]])

In [175]:
np.sort(arr)

array([[1, 3, 9],
       [6, 7, 8]])

In [176]:
np.sort(arr, axis=0)

array([[3, 1, 6],
       [8, 7, 9]])

In [177]:
np.sort(arr, axis=1)

array([[1, 3, 9],
       [6, 7, 8]])

### Stacking arrays

In [178]:
a = np.array([10, 20, 30])
b = np.array([15, 25, 35])

In [179]:
# vertical stacking
np.vstack((a, b))

array([[10, 20, 30],
       [15, 25, 35]])

In [180]:
# horizontal stacking
np.hstack((a, b))

array([10, 20, 30, 15, 25, 35])

In [181]:
# column stacking
np.column_stack((a, b))

array([[10, 15],
       [20, 25],
       [30, 35]])

### splitting

In [182]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
np.split(arr, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [185]:
# vertical split
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
np.vsplit(arr, 2)

[array([[10, 20, 30]]), array([[40, 50, 60]])]

### Matrix multiplication

In [186]:
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])

np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [187]:
# alternatively
A @ B

array([[19, 22],
       [43, 50]])

### Transpose

In [189]:
A

array([[1, 2],
       [3, 4]])

In [191]:
A.T   # T attribute is used to Transpose a matrix

array([[1, 3],
       [2, 4]])

### Inverse Matrix

In [192]:
A = np.array([
    [4, 5],
    [10, 7]
])

inv_A = np.linalg.inv(A)
inv_A

array([[-0.31818182,  0.22727273],
       [ 0.45454545, -0.18181818]])

In [194]:
A @ inv_A

array([[ 1.00000000e+00, -8.32667268e-17],
       [-4.44089210e-16,  1.00000000e+00]])

### Determinent of a Matrix

In [195]:
A

array([[ 4,  5],
       [10,  7]])

In [196]:
np.linalg.det(A)

-22.000000000000004

### EigenValue and EigenVectors

In [198]:
A  # squre matrix

array([[ 4,  5],
       [10,  7]])

In [199]:
values, vectors = np.linalg.eig(A)
print("Values:", values)
print("Vecotrs:", vectors)

Values: [-1.72841615 12.72841615]
Vecotrs: [[-0.65758314 -0.49706296]
 [ 0.75338198 -0.86771448]]


### Norm (Vector Magnitude)

In [200]:
A

array([[ 4,  5],
       [10,  7]])

In [201]:
np.linalg.norm(A)

13.784048752090222